"""Re-aim study.css's option and input rules at Dash 4's markup: writes `src/assets/zz-bridge.css`.

The design handoff's stylesheet (`src/assets/study.css`, copied unchanged) was written for markup
where a list of radios or checkboxes is a row of `<label class="chip"><input> text</label>`, with
the class on each label: `.chip`, `.ui-tile`, `.seg-item`. Dash 4's `dcc.RadioItems` and
`dcc.Checklist` cannot put a class on those labels. Each label is
`<label class="dash-options-list-option">`, and `labelClassName` goes on the text beside the
input. The list's own `className` does reach the element around the labels, so every such rule
can be matched as ".dash-options-list-option whose parent carries the list's class". Likewise
`dcc.Input` puts its `className` on a box around the `<input>`, so a state of the input itself,
such as `:focus-visible`, has to be read through that box with `:has()`.

This script copies every study.css rule that names one of those classes, with the selector
rewritten that way and the declarations untouched, so the bridge can never drift from the
stylesheet: `tests/test_stylesheet.py` fails if the file is not what this script writes. Rules
that exist only to preview a state in the handoff's component sheet (`.is-hover`, `.is-focus`,
`.is-selected`, `.is-disabled`, `.is-error`) are left out.

docs/visual-spec.md section 10. Re-run it after changing study.css or the classes below.

Usage:
    uv run python scripts/bridge_stylesheet.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STUDY = ROOT / "src" / "assets" / "study.css"
OUT = ROOT / "src" / "assets" / "zz-bridge.css"

# A class study.css puts on each option's label, and the class of the list around those labels.
OPTION_LISTS = {
    "ui-tile": "ui-tiles",
    "chip": "chips",
    "seg-item": "seg",
}
# Classes study.css puts on an <input>, which dcc.Input puts on the box around it instead.
INPUT_BOXES = ("tb-num",)

DASH_OPTION = "dash-options-list-option"
PREVIEW_ONLY = re.compile(r"\.is-(?:hover|focus|selected|disabled|error)(?![\w-])")
# At-rules whose blocks hold ordinary rules; anything else (keyframes) is copied from nowhere.
GROUPING = ("@media", "@container", "@supports")

HEADER = """\
/* ==========================================================================
   GENERATED by scripts/bridge_stylesheet.py from study.css; do not edit.
   study.css's rules for option lists and input boxes, with each selector re-aimed at the markup
   Dash 4 renders (see the script). The declarations are study.css's own.
   ========================================================================== */
"""


def _class(name: str) -> re.Pattern[str]:
    """`.name` as a whole class: `.chip` but not `.chips` or `.chip-name`."""
    return re.compile(r"\." + re.escape(name) + r"(?![\w-])")


def translate(selector: str) -> str | None:
    """The selector re-aimed at Dash's markup, or None when it needs no bridge."""
    if PREVIEW_ONLY.search(selector):
        return None
    bridged = selector
    for label, listing in OPTION_LISTS.items():
        bridged = _class(label).sub(f".{DASH_OPTION}:is(.{listing} > *)", bridged)
    for box in INPUT_BOXES:
        bridged = re.sub(
            r"\." + re.escape(box) + r":focus-visible(?![\w-])",
            f".{box}:has(:focus-visible)",
            bridged,
        )
    return bridged if bridged != selector else None


def _strip_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def _block_end(css: str, opening: int) -> int:
    """The index of the brace closing the block opened at `opening`."""
    depth = 0
    for index in range(opening, len(css)):
        if css[index] == "{":
            depth += 1
        elif css[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("Unbalanced braces in the stylesheet")


def _bridge_block(css: str, indent: str = "") -> list[str]:
    """Bridged rules for one block of CSS, recursing into @media and @container."""
    out: list[str] = []
    position = 0
    while True:
        opening = css.find("{", position)
        if opening < 0:
            return out
        prelude = " ".join(css[position:opening].split())
        closing = _block_end(css, opening)
        body = css[opening + 1 : closing]
        position = closing + 1
        if prelude.startswith("@"):
            if prelude.startswith(GROUPING):
                inner = _bridge_block(body, indent + "  ")
                if inner:
                    out += [f"{indent}{prelude} {{", *inner, f"{indent}}}"]
            continue
        selectors = [translate(" ".join(part.split())) for part in prelude.split(",")]
        selectors = [selector for selector in selectors if selector]
        if not selectors:
            continue
        declarations = "; ".join(" ".join(d.split()) for d in body.split(";") if d.strip())
        joined = f",\n{indent}".join(selectors)
        out.append(f"{indent}{joined} {{ {declarations}; }}")


def build(css: str) -> str:
    """zz-bridge.css for this study.css."""
    return HEADER + "\n".join(_bridge_block(_strip_comments(css))) + "\n"


def main() -> int:
    OUT.write_text(build(STUDY.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
