"""Vendor the map's geometry into `src/assets/geo_africa.js`, so no browser has to fetch it.

The study's map (`src/figures.py`, scope "africa" at 110m) is drawn by plotly.js, which by default
downloads the country shapes from Plotly's CDN, in the participant's browser, the moment the map
first renders. A slow or blocked CDN would then leave one task unanswerable mid-session. plotly.js
checks `window.PlotlyGeoAssets.topojson[<name>]` before fetching, so this script writes the same
file, unmodified, into a script Dash serves from `src/assets/` on every page.

The output is a generated file, committed so the deployment has it. Re-run this only if the map's
scope or resolution changes.

Usage:
    uv run python scripts/vendor_map_geometry.py
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import figures  # noqa: E402

# plotly.js 4's default `topojsonURL`, and the name it builds from the scope and resolution.
SOURCE_URL = "https://cdn.plot.ly/un/"
NAME = f"{figures.MAP_SCOPE}_{figures.MAP_RESOLUTION}m"
OUT = ROOT / "src" / "assets" / "geo_africa.js"
USER_AGENT = "vaccine-dashboard/0.1 (Occidental College senior comprehensive; research use)"

HEADER = """\
/* Map geometry for the study's map. GENERATED by scripts/vendor_map_geometry.py; do not edit.
 *
 * Source, unmodified: {url}
 * It is the file plotly.js would otherwise fetch from Plotly's CDN in each participant's browser.
 * plotly.js looks in window.PlotlyGeoAssets before fetching, so seeding it here keeps a
 * third-party download out of the middle of a task.
 */
window.PlotlyGeoAssets = window.PlotlyGeoAssets || {{ topojson: {{}} }};
window.PlotlyGeoAssets.topojson = window.PlotlyGeoAssets.topojson || {{}};
"""


def main() -> int:
    url = f"{SOURCE_URL}{NAME}.json"
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            payload = response.read().decode("utf-8")
    except (urllib.error.URLError, TimeoutError) as exc:
        print(f"Download failed: {exc}", file=sys.stderr)
        return 1
    topology = json.loads(payload)
    if topology.get("type") != "Topology" or "countries" not in topology.get("objects", {}):
        print(f"{url} is not the expected topojson", file=sys.stderr)
        return 1

    OUT.write_text(
        HEADER.format(url=url)
        + f'window.PlotlyGeoAssets.topojson["{NAME}"] = {payload.strip()};\n',
        encoding="utf-8",
        newline="\n",
    )
    count = len(topology["objects"]["countries"]["geometries"])
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB, {count} countries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
