"""Coverage data for the deployed app. Stdlib only.

**This module must never import pandas, numpy, or pyarrow.** Those three are 145 MB of the local
environment and would push the Vercel Python bundle past its limit; `tests/test_runtime_data.py`
fails the build if they appear here. Cleaning and validation live in `src/data.py`, which stays
pandas-based and runs offline.

Reads `data/deploy/coverage.csv`, generated by `scripts/export_deploy_data.py`. A missing value is
an empty field in the CSV and becomes `None` here — never 0, never skipped. Gaps are part of what
participants interpret.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

from src import config

DEPLOY_CSV = config.DATA_DIR / "deploy" / "coverage.csv"

EXPECTED_COLUMNS = ["country", "iso_code", "year", "vaccine", "coverage_pct"]


class RuntimeDataError(RuntimeError):
    """Raised when the deploy CSV is absent or malformed."""


@dataclass(frozen=True, slots=True)
class Row:
    """One entity x year x vaccine observation. `coverage_pct` is None when not reported."""

    country: str
    iso_code: str
    year: int
    vaccine: str
    coverage_pct: float | None


# Cached at module scope so a warm serverless container parses the CSV once, not per request.
_rows: tuple[Row, ...] | None = None


def clear_cache() -> None:
    """Drop the cached rows. For tests and for regeneration checks."""
    global _rows
    _rows = None


def load_rows(path: Path | None = None) -> tuple[Row, ...]:
    """Return every row from the deploy CSV, cached after the first call."""
    global _rows
    if _rows is not None and path is None:
        return _rows

    source = path or DEPLOY_CSV
    if not source.exists():
        raise RuntimeDataError(
            f"Deploy data not found at {source}. Run: uv run python scripts/export_deploy_data.py"
        )

    with source.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames != EXPECTED_COLUMNS:
            raise RuntimeDataError(
                f"Unexpected columns {reader.fieldnames}, expected {EXPECTED_COLUMNS}"
            )
        rows = tuple(_parse(record, index) for index, record in enumerate(reader, start=2))

    if not rows:
        raise RuntimeDataError(f"{source} contains no rows")

    if path is None:
        _rows = rows
    return rows


def _parse(record: dict[str, str], line: int) -> Row:
    raw = (record["coverage_pct"] or "").strip()
    try:
        coverage = float(raw) if raw else None
        year = int(record["year"])
    except ValueError as exc:
        raise RuntimeDataError(f"Malformed value on line {line}: {exc}") from exc

    if coverage is not None and not 0 <= coverage <= 100:
        raise RuntimeDataError(f"coverage_pct {coverage} outside 0-100 on line {line}")

    return Row(
        country=record["country"],
        iso_code=record["iso_code"],
        year=year,
        vaccine=record["vaccine"],
        coverage_pct=coverage,
    )


def series(country: str, vaccine: str, rows: tuple[Row, ...] | None = None) -> list[Row]:
    """Rows for one entity and vaccine, ordered by year, gaps included as None."""
    source = rows if rows is not None else load_rows()
    matching = [r for r in source if r.country == country and r.vaccine == vaccine]
    return sorted(matching, key=lambda r: r.year)


def entities(rows: tuple[Row, ...] | None = None) -> list[str]:
    """Every entity present, in the order given by config."""
    source = rows if rows is not None else load_rows()
    present = {r.country for r in source}
    return [e for e in config.ENTITIES if e in present]


def vaccines(rows: tuple[Row, ...] | None = None) -> list[str]:
    """Every vaccine present, in the order given by config."""
    source = rows if rows is not None else load_rows()
    present = {r.vaccine for r in source}
    return [v for v in config.VACCINES if v in present]
